name: uikit
description: "A new Flutter package project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  cached_network_image: ^3.4.1
  collection: ^1.19.0
  flutter:
    sdk: flutter
  flutter_form_builder: ^9.7.0
  flutter_keyboard_visibility: ^6.0.0
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.17
  intl: ^0.19.0
  modal_bottom_sheet: ^3.0.0
  top_snackbar_flutter: ^3.2.0

dev_dependencies:
  build_runner: ^2.4.11
  flutter_test:
    sdk: flutter
  spider: ^4.2.2

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/fonts/

  fonts:
    - family: SFUIText
      fonts:
        - asset: assets/fonts/SFUIText/SFUIText-Bold.ttf
        - asset: assets/fonts/SFUIText/SFUIText-BoldItalic.ttf
        - asset: assets/fonts/SFUIText/SFUIText-Heavy.ttf
        - asset: assets/fonts/SFUIText/SFUIText-HeavyItalic.ttf
        - asset: assets/fonts/SFUIText/SFUIText-Light.ttf
        - asset: assets/fonts/SFUIText/SFUIText-LightItalic.ttf
        - asset: assets/fonts/SFUIText/SFUIText-Medium.ttf
        - asset: assets/fonts/SFUIText/SFUIText-MediumItalic.ttf
        - asset: assets/fonts/SFUIText/SFUIText-Regular.ttf
        - asset: assets/fonts/SFUIText/SFUIText-RegularItalic.ttf
        - asset: assets/fonts/SFUIText/SFUIText-Semibold.ttf
        - asset: assets/fonts/SFUIText/SFUIText-SemiboldItalic.ttf

flutter_intl:
  enabled: true
