name: starter
description: "Mobile application for starter"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  auto_route: ^9.2.2
  bloc: ^9.0.0
  bloc_concurrency: ^0.3.0
  collection: ^1.19.1
  dio: ^5.9.0
  equatable: ^2.0.7
  flutter_bloc: ^9.1.1
  flutter_form_builder: ^10.1.0
  flutter_native_splash: ^2.4.6
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.2.1
  freezed_annotation: ^2.4.4
  get_it: ^8.2.0
  intl: ^0.20.2
  intl_utils: ^2.8.8
  retrofit: ^4.7.2
  rxdart: ^0.28.0
  shared_preferences: ^2.5.3
  starter_toolkit:
    path: ./packages/starter_toolkit
  starter_uikit:
    path: ./packages/starter_uikit

dev_dependencies:
  flutter_test:
    sdk: flutter
  analyzer: ^7.7.1
  auto_route_generator: ^9.3.1
  bloc_test: ^10.0.0
  build_runner: ^2.4.0
  flutter_gen_runner: ^5.12.0
  flutter_launcher_icons: ^0.14.4
  freezed: ^2.5.8
  json_serializable: ^6.9.5
  mocktail: ^1.0.4
  retrofit_generator: ^9.7.0


flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

flutter_intl:
  enabled: true
  main_locale: en
  class_name: Localizer
  output_dir: lib/l10n/generated