name: starter_toolkit

description: "Mobile application for starter"

publish_to: 'none'

version: 1.0.0+1

dependency_overrides:
  analyzer: 7.7.1
  test_api: 0.7.4

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^9.2.2
  collection: ^1.19.1
  dio: ^5.9.0
  equatable: ^2.0.7
  flutter_bloc: ^9.1.1
  flutter_form_builder: ^10.1.0
  freezed_annotation: ^2.4.4
  http_parser: ^4.1.2
  image_gallery_saver:
    git:
      url: https://github.com/benlrichards/image_gallery_saver
  image_picker: ^1.2.0
  intl: ^0.20.2
  intl_utils: ^2.8.8
  mask_text_input_formatter: ^2.9.0
  permission_handler: ^12.0.1
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.0
  freezed: ^2.5.8
  json_serializable: ^6.9.5

flutter:
  uses-material-design: true

flutter_intl:
  enabled: true
  main_locale: en
  class_name: ToolkitLocalizer
  output_dir: lib/l10n/generated